# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20170824_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='textss',
        ),
    ]
