# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20170824_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerA',
        ),
    ]
