# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0006_auto_20170824_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question')),
            ],
            options={
                'db_table': 'Answer',
            },
        ),
        migrations.RemoveField(
            model_name='answera',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answera',
            name='question',
        ),
        migrations.DeleteModel(
            name='AnswerA',
        ),
    ]
